### ISSUE TITLE
convert wav to mp3

### ISSUE THREAD

**Issue by therewasaguy** [jdiedrick/transients-server#16]
It takes a long time to load all the wav files. We need a server-side script to convert to mp3.

**Comment by johanndiedrick** [comment]
http://stackoverflow.com/questions/10287683/python-convert-wav-to-mp3

http://stackoverflow.com/questions/890552/mp3-coversion-on-amazons-ec2

https://stedolan.github.io/jq/manual

https://zerokspot.com/weblog/2013/07/18/processing-json-with-jq/

https://robots.thoughtbot.com/jq-is-sed-for-json

http://stackoverflow.com/questions/9865866/pipe-output-of-cat-to-curl-to-download-a-list-of-files

http://stackoverflow.com/questions/6114119/how-do-i-read-first-line-using-cat

http://stackoverflow.com/questions/8659382/downloading-an-entire-s3-bucket

http://stackoverflow.com/questions/15050146/is-it-possible-to-perform-a-batch-upload-to-amazon-s3

**Comment by therewasaguy** [comment]
nice work @jdiedrick !
